# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET 7.0
on:
  push:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - uses:  ./HearthstoneAPIClient
      with:
        test-assembly-path: RunSpecflowTests/bin/Release/net7.0
        test-assembly-dll: RunSpecflowTests.dll
        output-html: CalculatorResults.html
        framework: net6.0
